-- =========================================
-- 05_audit.sql
-- Author: Fahimeh Latifi
-- Description: Audit & Logging Table for ERP system
-- =========================================

CREATE TABLE audit_log (
    audit_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name      VARCHAR2(100) NOT NULL,
    record_id       NUMBER,
    operation_type  VARCHAR2(10) CHECK(operation_type IN ('INSERT','UPDATE','DELETE')),
    old_values      CLOB,
    new_values      CLOB,
    changed_by      VARCHAR2(100),
    change_date     DATE DEFAULT SYSDATE,
    description     VARCHAR2(500)
);