-- =========================================
-- 04_finance.sql
-- Author: Fahimeh Latifi
-- Description: Account Ledger, Sub Accounts, Payments & Shipments
-- =========================================

-- ======================================================
--  Sub Accounts
-- Defines sub-codes for parties, projects, orders, employees, etc.
-- ======================================================
CREATE TABLE sub_accounts (
    sub_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub_code        VARCHAR2(30) UNIQUE NOT NULL,
    sub_name        VARCHAR2(200) NOT NULL,
    sub_type        VARCHAR2(30) CHECK(sub_type IN 
                     ('PARTY','PROJECT','ORDER','EMPLOYEE','OTHER')),
    description     VARCHAR2(500)
);

-- ======================================================
--  General Ledger
-- Unified ledger for debit/credit transactions
-- ======================================================
CREATE TABLE account_ledger (
    ledger_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_code    VARCHAR2(30) NOT NULL,
    sub_code        VARCHAR2(30) NOT NULL,
    reference_type  VARCHAR2(30),
    reference_id    NUMBER,
    debit_amount    NUMBER(18,2) DEFAULT 0,
    credit_amount   NUMBER(18,2) DEFAULT 0,
    entry_date      DATE DEFAULT SYSDATE,
    description     VARCHAR2(500),
    CONSTRAINT fk_ledger_sub
        FOREIGN KEY (sub_code)
        REFERENCES sub_accounts(sub_code)
);

-- ======================================================
--  Payments
-- Payments linked to sales orders or purchase requests
-- ======================================================
CREATE TABLE payments (
    payment_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_type  VARCHAR2(30) CHECK(reference_type IN ('SALES_ORDER','PURCHASE_REQUEST')),
    reference_id    NUMBER NOT NULL,
    payment_date    DATE DEFAULT SYSDATE,
    amount          NUMBER(18,2) NOT NULL,
    payment_method  VARCHAR2(50),
    status          VARCHAR2(30) CHECK(status IN ('PENDING','COMPLETED','FAILED')),
    description     VARCHAR2(500)
);

-- ======================================================
--  Shipments
-- Linked to sales orders
-- ======================================================
CREATE TABLE shipments (
    shipment_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_id           NUMBER NOT NULL,
    shipped_date    DATE DEFAULT SYSDATE,
    delivery_date   DATE,
    shipment_status VARCHAR2(30) CHECK(shipment_status IN ('PENDING','SHIPPED','DELIVERED','CANCELLED')),
    carrier_name    VARCHAR2(100),
    tracking_no     VARCHAR2(50),
    description     VARCHAR2(500),
    CONSTRAINT fk_ship_so
        FOREIGN KEY (so_id)
        REFERENCES sales_orders(so_id)
);