-- =========================================
-- 03_procurement.sql
-- Author: Fahimeh Latifi
-- Description: Purchase Requests, Items & 3-Level Approval Workflow
-- =========================================

-- ======================================================
--  Purchase Requests (Header)
-- Each request is linked to a project
-- ======================================================
CREATE TABLE purchase_requests (
    pr_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      NUMBER NOT NULL,
    request_date    DATE DEFAULT SYSDATE,
    requested_by    VARCHAR2(100),
    total_amount    NUMBER(18,2),
    status          VARCHAR2(30) DEFAULT 'PENDING_L1' CHECK (
                       status IN ('PENDING_L1','PENDING_L2','PENDING_L3','APPROVED','REJECTED')
                   ),
    description     VARCHAR2(500),
    CONSTRAINT fk_pr_project
        FOREIGN KEY (project_id)
        REFERENCES projects(project_id)
);

-- ======================================================
-- Purchase Request Items (Detail)
-- Each item belongs to a purchase request
-- ======================================================
CREATE TABLE purchase_request_items (
    item_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pr_id           NUMBER NOT NULL,
    item_code       VARCHAR2(50),
    item_desc       VARCHAR2(300),
    quantity        NUMBER,
    unit_price      NUMBER(18,2),
    total_price     NUMBER(18,2),
    CONSTRAINT fk_pr_item
        FOREIGN KEY (pr_id)
        REFERENCES purchase_requests(pr_id)
);

-- ======================================================
-- Approval Workflow Table
-- Tracks 3 levels of approval per request
-- ======================================================
CREATE TABLE pr_approval (
    approval_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pr_id           NUMBER NOT NULL,
    level_no        NUMBER CHECK(level_no IN (1,2,3)),
    approver_name   VARCHAR2(100),
    approved_flag   CHAR(1) CHECK(approved_flag IN ('Y','N')),
    approved_date   DATE,
    comments        VARCHAR2(500),
    CONSTRAINT fk_approval_pr
        FOREIGN KEY (pr_id)
        REFERENCES purchase_requests(pr_id)
);