-- =========================================
-- projects.sql
-- Author: Fahimeh Latifi
-- Description: Projects & Contracts schema
-- =========================================

-- Business Parties
CREATE TABLE business_parties (
    party_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_code      VARCHAR2(30) UNIQUE NOT NULL,
    party_name      VARCHAR2(200) NOT NULL,
    party_type      VARCHAR2(30) CHECK (party_type IN ('CUSTOMER','SUPPLIER','CONTRACTOR')),
    tax_id          VARCHAR2(50),
    created_at      DATE DEFAULT SYSDATE
);

-- Contracts
CREATE TABLE contracts (
    contract_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_number  VARCHAR2(50) UNIQUE NOT NULL,
    party_id         NUMBER NOT NULL,
    contract_amount  NUMBER(18,2),
    start_date       DATE,
    end_date         DATE,
    status           VARCHAR2(30) CHECK (status IN ('ACTIVE','CLOSED','SUSPENDED')),
    CONSTRAINT fk_contract_party
        FOREIGN KEY (party_id) 
        REFERENCES business_parties(party_id)
);

-- Projects
CREATE TABLE projects (
    project_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code    VARCHAR2(30) UNIQUE NOT NULL,
    contract_id     NUMBER NOT NULL,
    project_name    VARCHAR2(200),
    budget_amount   NUMBER(18,2),
    start_date      DATE,
    end_date        DATE,
    status          VARCHAR2(30) CHECK (status IN ('ACTIVE','CLOSED','ON_HOLD')),
    CONSTRAINT fk_project_contract
        FOREIGN KEY (contract_id) 
        REFERENCES contracts(contract_id)
);