-- =========================================
-- 02_sales.sql
-- Author: Fahimeh Latifi
-- Description: Sales Orders & Sales Order Items schema
-- =========================================

-- ======================================================
-- Sales Orders (Header)
-- Each order is linked to a project
-- ======================================================
CREATE TABLE sales_orders (
    so_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      NUMBER NOT NULL,
    order_date      DATE DEFAULT SYSDATE,
    total_amount    NUMBER(18,2),
    status          VARCHAR2(30) CHECK (status IN ('PENDING','APPROVED','SHIPPED','CLOSED')),
    created_by      VARCHAR2(100),
    description     VARCHAR2(500),
    CONSTRAINT fk_so_project
        FOREIGN KEY (project_id)
        REFERENCES projects(project_id)
);

-- ======================================================
--Sales Order Items (Detail)
-- Each item belongs to a sales order
-- ======================================================
CREATE TABLE sales_order_items (
    item_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_id           NUMBER NOT NULL,
    product_code    VARCHAR2(50),
    item_desc       VARCHAR2(300),
    quantity        NUMBER,
    unit_price      NUMBER(18,2),
    total_price     NUMBER(18,2),
    CONSTRAINT fk_so_item
        FOREIGN KEY (so_id)
        REFERENCES sales_orders(so_id)
);